default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: e_learning_ren_development

test:
  <<: *default
  database: e_learning_ren_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: e_learning_ren_production
  username: e_learning_ren
  password: <%= ENV['E_LEARNING_REN_DATABASE_PASSWORD'] %>